"use client"
import {useEffect,useState} from "react"
import AdminShell from "@/components/AdminShell"
export default function ContentAdmin(){
 const[ops,setOps]=useState<any>(null),[saved,setSaved]=useState(false)
 useEffect(()=>{fetch("/api/admin/operations").then(r=>r.json()).then(setOps)},[])
 const save=async()=>{const r=await fetch("/api/admin/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"site-content",patch:ops.siteContent})});if(r.ok){setOps(await r.json());setSaved(true);setTimeout(()=>setSaved(false),1700)}}
 if(!ops)return <AdminShell><section className="adminPageV2">Loading…</section></AdminShell>
 return <AdminShell><section className="adminPageV2"><div className="pageHeadV2"><div><span>Website</span><h1>Homepage content</h1><p>Change the public message without touching code.</p></div><button className="adminPrimaryV2" onClick={save}>{saved?"✓ Saved":"Save homepage"}</button></div>
  <section className="adminSectionCardV2"><div className="sectionTitleV2"><div><h2>Hero section</h2><p>The first message visitors see.</p></div></div><div className="contentFormV2"><label>Small heading<input value={ops.siteContent.eyebrow} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,eyebrow:e.target.value}})}/></label><label>Main heading<input value={ops.siteContent.heroTitle} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,heroTitle:e.target.value}})}/></label><label>Highlighted words<input value={ops.siteContent.heroAccent} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,heroAccent:e.target.value}})}/></label><label className="wideV2">Description<textarea value={ops.siteContent.heroBody} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,heroBody:e.target.value}})}/></label></div></section>
  <section className="adminSectionCardV2"><div className="sectionTitleV2"><div><h2>Company objectives</h2><p>Explain what Aether exists to do.</p></div></div><div className="contentFormV2"><label>Heading<input value={ops.siteContent.objectiveTitle} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,objectiveTitle:e.target.value}})}/></label><label className="wideV2">Description<textarea value={ops.siteContent.objectiveBody} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,objectiveBody:e.target.value}})}/></label></div></section>
  <section className="adminSectionCardV2"><div className="sectionTitleV2"><div><h2>What Aether offers</h2><p>Each card appears on the homepage.</p></div></div><div className="offerEditorGridV2">{ops.siteContent.offers.map((o:any,i:number)=><article key={o.id}><span>Card {i+1}</span><label>Category<input value={o.kicker} onChange={e=>{const a=[...ops.siteContent.offers];a[i]={...o,kicker:e.target.value};setOps({...ops,siteContent:{...ops.siteContent,offers:a}})}}/></label><label>Title<input value={o.title} onChange={e=>{const a=[...ops.siteContent.offers];a[i]={...o,title:e.target.value};setOps({...ops,siteContent:{...ops.siteContent,offers:a}})}}/></label><label>Description<textarea value={o.body} onChange={e=>{const a=[...ops.siteContent.offers];a[i]={...o,body:e.target.value};setOps({...ops,siteContent:{...ops.siteContent,offers:a}})}}/></label></article>)}</div></section>
  <button className="adminPrimaryV2 mobileSaveV2" onClick={save}>{saved?"✓ Homepage saved":"Save all homepage changes"}</button>
 </section></AdminShell>
}
