"use client"
import {useEffect,useState} from "react"
import AdminShell from "@/components/AdminShell"
export default function ContentAdmin(){
 const[ops,setOps]=useState<any>(null),[saved,setSaved]=useState(false)
 const[doc,setDoc]=useState<any>(null),[docStatus,setDocStatus]=useState(""),[uploading,setUploading]=useState(false)
 const loadDoc=()=>fetch("/api/admin/client-document",{cache:"no-store"}).then(r=>r.json()).then(d=>setDoc(d.document||null))
 useEffect(()=>{fetch("/api/admin/operations").then(r=>r.json()).then(setOps);loadDoc()},[])
 const save=async()=>{const r=await fetch("/api/admin/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"site-content",patch:ops.siteContent})});if(r.ok){setOps(await r.json());setSaved(true);setTimeout(()=>setSaved(false),1700)}}
 const uploadPdf=async(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;setUploading(true);setDocStatus("");const fd=new FormData();fd.append("file",f);const r=await fetch("/api/admin/client-document",{method:"POST",body:fd});const d=await r.json().catch(()=>({}));if(!r.ok)setDocStatus(d.error||"Upload failed.");else{setDoc(d.document);setDocStatus("PDF updated successfully.")}setUploading(false);e.target.value=""}
 if(!ops)return <AdminShell><section className="adminPageV2">Loading...</section></AdminShell>
 return <AdminShell><section className="adminPageV2">
  <div className="pageHeadV2"><div><span>Website</span><h1>Homepage content</h1><p>Change the public message and client documents without touching code.</p></div><button className="adminPrimaryV2" onClick={save}>{saved?"Saved":"Save homepage"}</button></div>
  <section className="adminSectionCardV2 clientPdfAdminCard"><div className="sectionTitleV2"><div><h2>Client Relationship Summary</h2><p>Upload the PDF clients see and download from their Overview page.</p></div></div><div className="pdfAdminBody"><div className="pdfAdminStatus"><div className="pdfAdminIcon">PDF</div><div><small>Current document</small><b>{doc?.filename||"Default AetherCM relationship summary"}</b><span>{doc?.uploadedAt?`Last updated ${new Date(doc.uploadedAt).toLocaleString()}`:"The built-in PDF is currently active."}</span></div></div><div className="pdfAdminActions"><label className="adminPrimaryV2 uploadPdfBtn">{uploading?"Uploading...":"Upload new PDF"}<input type="file" accept="application/pdf" onChange={uploadPdf} disabled={uploading}/></label><a className="adminSecondaryV2" href="/api/client-document" target="_blank" rel="noreferrer">Preview current PDF</a></div><p className="pdfAdminHint">Maximum 10 MB. Uploading a new PDF automatically makes it the document all clients see.</p>{docStatus&&<div className="pdfAdminMessage">{docStatus}</div>}</div></section>
  <section className="adminSectionCardV2"><div className="sectionTitleV2"><div><h2>Hero section</h2><p>The first message visitors see.</p></div></div><div className="contentFormV2"><label>Small heading<input value={ops.siteContent.eyebrow} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,eyebrow:e.target.value}})}/></label><label>Main heading<input value={ops.siteContent.heroTitle} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,heroTitle:e.target.value}})}/></label><label>Highlighted words<input value={ops.siteContent.heroAccent} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,heroAccent:e.target.value}})}/></label><label className="wideV2">Description<textarea value={ops.siteContent.heroBody} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,heroBody:e.target.value}})}/></label></div></section>
  <section className="adminSectionCardV2"><div className="sectionTitleV2"><div><h2>Company objectives</h2><p>Explain what Aether exists to do.</p></div></div><div className="contentFormV2"><label>Heading<input value={ops.siteContent.objectiveTitle} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,objectiveTitle:e.target.value}})}/></label><label className="wideV2">Description<textarea value={ops.siteContent.objectiveBody} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,objectiveBody:e.target.value}})}/></label></div></section>
  <section className="adminSectionCardV2"><div className="sectionTitleV2"><div><h2>What Aether offers</h2><p>Each card appears on the homepage.</p></div></div><div className="offerEditorGridV2">{ops.siteContent.offers.map((o:any,i:number)=><article key={o.id}><span>Card {i+1}</span><label>Category<input value={o.kicker} onChange={e=>{const a=[...ops.siteContent.offers];a[i]={...o,kicker:e.target.value};setOps({...ops,siteContent:{...ops.siteContent,offers:a}})}}/></label><label>Title<input value={o.title} onChange={e=>{const a=[...ops.siteContent.offers];a[i]={...o,title:e.target.value};setOps({...ops,siteContent:{...ops.siteContent,offers:a}})}}/></label><label>Description<textarea value={o.body} onChange={e=>{const a=[...ops.siteContent.offers];a[i]={...o,body:e.target.value};setOps({...ops,siteContent:{...ops.siteContent,offers:a}})}}/></label></article>)}</div></section>
  <button className="adminPrimaryV2 mobileSaveV2" onClick={save}>{saved?"Homepage saved":"Save all homepage changes"}</button>
 </section></AdminShell>
}
