'use client'
import { useEffect,useMemo,useState } from 'react'
import Link from 'next/link'
import Logo from '@/components/Logo'
import { Icon } from '@/components/Icons'
import type { AdminState } from '@/lib/data'
import type { AccountAdjustment,DailyGainRule,ShareAllocation,ShareControl,FundingMethod,TransferRequest } from '@/lib/ops'
const users=[['AC-20491','Maya Chen','maya@example.com','$123,305','Active'],['AC-20492','Daniel Reed','daniel@example.com','$84,510','Active'],['AC-20493','Priya Shah','priya@example.com','$42,889','Review'],['AC-20494','Noah Brooks','noah@example.com','$18,220','Restricted']]

type Ops={allocations:ShareAllocation[];adjustments:AccountAdjustment[];dailyGain:DailyGainRule;shareControls:ShareControl[];fundingMethods:FundingMethod[];transfers:TransferRequest[];cryptoGateway:any}
export default function Admin(){
 const [s,setS]=useState<AdminState|null>(null); const [ops,setOps]=useState<Ops|null>(null); const [amount,setAmount]=useState(''); const [note,setNote]=useState('');
 useEffect(()=>{fetch('/api/admin/state').then(r=>r.json()).then(setS); fetch('/api/admin/operations').then(r=>r.json()).then(setOps)},[])
 const patch=async(k:keyof AdminState,v:any)=>{const n=await fetch('/api/admin/state',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({[k]:v})}).then(r=>r.json());setS(n)}
 const op=async(body:any)=>{const r=await fetch('/api/admin/operations',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}); const n=await r.json(); if(r.ok)setOps(n); else alert(n.error||'Action failed')}
 const pending=useMemo(()=>ops?.allocations.filter(x=>x.status==='Pending')||[],[ops])
 return <div className="adminFrame"><aside className="adminSide"><Link href="/"><Logo/></Link><span className="adminBadge">ADMIN CONTROL</span><nav><a className="active"><Icon name="spark"/>Overview</a><a><Icon name="user"/>Clients</a><a><Icon name="wallet"/>Accounts</a><a><Icon name="trend"/>Allocations</a><a><Icon name="plus"/>Transfers</a><a><Icon name="chat"/>Live chat</a></nav><Link href="/dashboard" className="ghostBtn">Client view</Link></aside><main className="adminMain"><div className="adminTop"><div><span className="eyebrow">Operations console</span><h1>Aether Control Center</h1><p>Account controls, allocations, support and platform operations.</p></div><span className="statusPill">● Systems nominal</span></div>
 <div className="adminStats"><div><small>Total client assets</small><b>$18.42M</b><span>+4.8% this month</span></div><div><small>Active accounts</small><b>1,284</b><span>42 pending review</span></div><div><small>Pending allocations</small><b>{pending.length}</b><span>Require admin decision</span></div><div><small>Open chats</small><b>7</b><span>3 high priority</span></div></div>
 {s&&<div className="adminGrid"><section className="panel"><div className="panelHead"><h3>Platform controls</h3><span>Live configuration</span></div><div className="toggleList">{([['registrations','New registrations'],['withdrawals','Withdrawals'],['trading','Trading'],['liveChat','Live chat'],['maintenance','Maintenance mode']] as [keyof AdminState,string][]).map(([k,label])=><label key={k}><span><b>{label}</b><small>Platform-wide operational switch</small></span><input type="checkbox" checked={Boolean(s[k])} onChange={e=>patch(k,e.target.checked)}/></label>)}</div><label className="noticeEditor">Platform notice<textarea value={s.heroNotice} onChange={e=>setS({...s,heroNotice:e.target.value})}/><button className="ghostBtn" onClick={()=>patch('heroNotice',s.heroNotice)}>Save notice</button></label></section>
 <section className="panel"><div className="panelHead"><h3>Live support queue</h3><span>7 open</span></div><div className="supportQueue"><div><span className="avatar">MC</span><div><b>Maya Chen</b><small>Withdrawal pending 2h</small></div><button>Open</button></div><div><span className="avatar">DR</span><div><b>Daniel Reed</b><small>Order question · 4m</small></div><button>Open</button></div><div><span className="avatar">PS</span><div><b>Priya Shah</b><small>Identity review · 11m</small></div><button>Open</button></div></div></section></div>}
 {ops&&<><div className="adminGrid opsGrid"><section className="panel"><div className="panelHead"><h3>Account balance adjustment</h3><span>Audited admin action</span></div><p className="subtle">Credit or debit a client ledger with a visible reason. This is an administrative adjustment, not market performance.</p><div className="compactForm"><select><option>Maya Chen · AC-20491</option></select><input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="+500 or -250"/><input value={note} onChange={e=>setNote(e.target.value)} placeholder="Reason / reference"/><button className="solidBtn small" onClick={()=>{op({action:'adjust-balance',userId:'AC-20491',userName:'Maya Chen',amount:Number(amount),note});setAmount('');setNote('')}}>Apply adjustment</button></div><div className="miniLedger">{ops.adjustments.slice(0,4).map(a=><div key={a.id}><span><b>{a.kind}</b><small>{a.userName} · {a.note}</small></span><strong className={a.amount>=0?'good':'bad'}>{a.amount>=0?'+':''}${Math.abs(a.amount).toLocaleString()}</strong></div>)}</div></section>
 <section className="panel"><div className="panelHead"><h3>Automatic daily gain rule</h3><span>{ops.dailyGain.enabled?'Enabled':'Off'}</span></div><p className="subtle">For managed/simulated programs only. Accruals must be booked as a separate ledger event—not presented as live market profit.</p><div className="ruleGrid"><label>Enabled<input type="checkbox" checked={ops.dailyGain.enabled} onChange={e=>op({action:'daily-gain',rule:{enabled:e.target.checked}})}/></label><label>Mode<select value={ops.dailyGain.mode} onChange={e=>op({action:'daily-gain',rule:{mode:e.target.value}})}><option value="percent">Percent</option><option value="fixed">Fixed amount</option></select></label><label>Daily value<input value={ops.dailyGain.value} type="number" step="0.01" onChange={e=>setOps({...ops,dailyGain:{...ops.dailyGain,value:Number(e.target.value)}})} onBlur={()=>op({action:'daily-gain',rule:{value:ops.dailyGain.value}})}/></label><label>Scope<select value={ops.dailyGain.scope} onChange={e=>op({action:'daily-gain',rule:{scope:e.target.value}})}><option value="managed-only">Managed accounts only</option><option value="all">All eligible accounts</option></select></label></div></section></div>
 <section className="panel allocationPanel"><div className="panelHead"><h3>Share allocation approvals</h3><span>{pending.length} pending</span></div><div className="allocationTable"><div className="allocTR head"><span>Client</span><span>Asset</span><span>Shares</span><span>Value</span><span>Status</span><span>Decision</span></div>{ops.allocations.map(a=><div className="allocTR" key={a.id}><span><b>{a.userName}</b><small>{a.userId}</small></span><span><b>{a.symbol}</b><small>{a.name}</small></span><span>{a.shares}</span><span>${a.value.toLocaleString(undefined,{maximumFractionDigits:2})}</span><span className={a.status.toLowerCase()}>{a.status}</span><span className="decisionBtns">{a.status==='Pending'?<><button className="approve" onClick={()=>op({action:'allocation-status',id:a.id,status:'Approved'})}>Approve</button><button className="reject" onClick={()=>op({action:'allocation-status',id:a.id,status:'Rejected'})}>Reject</button></>:<small>Completed</small>}</span></div>)}</div></section>
 <section className="panel allocationPanel"><div className="panelHead"><h3>Share controls</h3><span>Admin allocation policy</span></div><div className="shareControlGrid">{ops.shareControls.map(c=><div className="shareControl" key={c.symbol}><div><span className="assetBadge">{c.symbol[0]}</span><span><b>{c.symbol}</b><small>{c.name}</small></span></div><label>Enabled<input type="checkbox" checked={c.enabled} onChange={e=>op({action:'share-control',symbol:c.symbol,patch:{enabled:e.target.checked}})}/></label><label>Approval<input type="checkbox" checked={c.approvalRequired} onChange={e=>op({action:'share-control',symbol:c.symbol,patch:{approvalRequired:e.target.checked}})}/></label><label>Manual quote $<input type="number" step="0.01" value={c.manualPrice} onChange={e=>setOps({...ops,shareControls:ops.shareControls.map(x=>x.symbol===c.symbol?{...x,manualPrice:Number(e.target.value)}:x)})} onBlur={()=>op({action:'share-control',symbol:c.symbol,patch:{manualPrice:c.manualPrice}})}/></label><label>Min request $<input type="number" value={c.minAmount} onChange={e=>setOps({...ops,shareControls:ops.shareControls.map(x=>x.symbol===c.symbol?{...x,minAmount:Number(e.target.value)}:x)})} onBlur={()=>op({action:'share-control',symbol:c.symbol,patch:{minAmount:c.minAmount}})}/></label><label>Max request $<input type="number" value={c.maxAmount} onChange={e=>setOps({...ops,shareControls:ops.shareControls.map(x=>x.symbol===c.symbol?{...x,maxAmount:Number(e.target.value)}:x)})} onBlur={()=>op({action:'share-control',symbol:c.symbol,patch:{maxAmount:c.maxAmount}})}/></label><label>Max shares<input type="number" value={c.maxShares} onChange={e=>setOps({...ops,shareControls:ops.shareControls.map(x=>x.symbol===c.symbol?{...x,maxShares:Number(e.target.value)}:x)})} onBlur={()=>op({action:'share-control',symbol:c.symbol,patch:{maxShares:c.maxShares}})}/></label><label>Portfolio cap %<input type="number" value={c.allocationCapPct} onChange={e=>setOps({...ops,shareControls:ops.shareControls.map(x=>x.symbol===c.symbol?{...x,allocationCapPct:Number(e.target.value)}:x)})} onBlur={()=>op({action:'share-control',symbol:c.symbol,patch:{allocationCapPct:c.allocationCapPct}})}/></label></div>)}</div></section></>}


 <section className="panel allocationPanel"><div className="panelHead"><h3>Manual crypto gateway</h3><span>Admin-controlled</span></div>
 <div className="adminFormGrid">
   <label>Gateway enabled<input type="checkbox" checked={ops.cryptoGateway.enabled} onChange={e=>op({action:'crypto-gateway',patch:{enabled:e.target.checked}})}/></label>
   <label>Payment timer (minutes)<input type="number" value={ops.cryptoGateway.paymentWindowMinutes} onChange={e=>setOps({...ops,cryptoGateway:{...ops.cryptoGateway,paymentWindowMinutes:Number(e.target.value)}})} onBlur={()=>op({action:'crypto-gateway',patch:{paymentWindowMinutes:ops.cryptoGateway.paymentWindowMinutes}})}/></label>
   <label className="wideControl">Customer instructions<textarea value={ops.cryptoGateway.instructions} onChange={e=>setOps({...ops,cryptoGateway:{...ops.cryptoGateway,instructions:e.target.value}})} onBlur={()=>op({action:'crypto-gateway',patch:{instructions:ops.cryptoGateway.instructions}})}/></label>
 </div>
 <div className="shareControlGrid">{ops.cryptoGateway.addresses.map((a:any)=><div className="shareControl" key={a.id}><div><span className="assetBadge">₿</span><span><b>{a.asset}</b><small>{a.network}</small></span></div><label>Enabled<input type="checkbox" checked={a.enabled} onChange={e=>op({action:'crypto-address',id:a.id,patch:{enabled:e.target.checked}})}/></label><label className="wideControl">Deposit address<input value={a.address} onChange={e=>setOps({...ops,cryptoGateway:{...ops.cryptoGateway,addresses:ops.cryptoGateway.addresses.map((x:any)=>x.id===a.id?{...x,address:e.target.value}:x)}})} onBlur={()=>op({action:'crypto-address',id:a.id,patch:{address:a.address}})}/></label><label>Minimum deposit $<input type="number" value={a.minDeposit} onChange={e=>setOps({...ops,cryptoGateway:{...ops.cryptoGateway,addresses:ops.cryptoGateway.addresses.map((x:any)=>x.id===a.id?{...x,minDeposit:Number(e.target.value)}:x)}})} onBlur={()=>op({action:'crypto-address',id:a.id,patch:{minDeposit:a.minDeposit}})}/></label></div>)}</div>
 <div className="complianceNote">Users only see enabled crypto addresses. A timed deposit request is created, then the user submits a TXID. Admin verifies the transaction manually before completing the deposit and crediting the balance.</div>
 </section>

 <section className="panel allocationPanel"><div className="panelHead"><h3>Funding & withdrawal gateways</h3><span>Crypto primary</span></div><div className="shareControlGrid">{ops.fundingMethods.map(m=><div className="shareControl" key={m.id}><div><span className="assetBadge">{m.id==='crypto'?'₿':m.id==='wire'?'$':'P'}</span><span><b>{m.label}</b><small>{m.primary?'Primary gateway':'Secondary gateway'}</small></span></div><label>Enabled<input type="checkbox" checked={m.enabled} onChange={e=>op({action:'funding-method',id:m.id,patch:{enabled:e.target.checked}})}/></label><label className="wideControl">Instructions<textarea value={m.instructions} onChange={e=>setOps({...ops,fundingMethods:ops.fundingMethods.map(x=>x.id===m.id?{...x,instructions:e.target.value}:x)})} onBlur={()=>op({action:'funding-method',id:m.id,patch:{instructions:m.instructions}})}/></label></div>)}</div></section>
 <section className="panel allocationPanel"><div className="panelHead"><h3>Deposit & withdrawal approvals</h3><span>{ops.transfers.filter(t=>t.status==='Pending').length} pending</span></div><div className="allocationTable"><div className="allocTR head"><span>Client</span><span>Direction</span><span>Method</span><span>Amount</span><span>Status</span><span>Decision</span></div>{ops.transfers.map(t=><div className="allocTR" key={t.id}><span><b>{t.userName}</b><small>{t.userId}</small></span><span>{t.direction}</span><span>{t.method.toUpperCase()}</span><span>${t.amount.toLocaleString()}</span><span className={t.status.toLowerCase()}>{t.status}</span><span className="decisionBtns">{t.status==='Pending'?<><button className="approve" onClick={()=>op({action:'transfer-status',id:t.id,status:'Completed'})}>Complete</button><button className="reject" onClick={()=>op({action:'transfer-status',id:t.id,status:'Rejected'})}>Reject</button></>:<small>Completed</small>}</span></div>)}</div></section>

 <section className="panel adminUsers"><div className="panelHead"><h3>Client accounts</h3><div><button className="ghostBtn">Export</button><button className="solidBtn small">Create client</button></div></div><div className="adminTable"><div className="adminTR head"><span>Account</span><span>Client</span><span>Email</span><span>Assets</span><span>Status</span><span></span></div>{users.map(u=><div className="adminTR" key={u[0]}>{u.map((v,i)=><span key={i} className={i===4?v.toLowerCase():''}>{v}</span>)}<button>Manage</button></div>)}</div></section>
 <div className="adminNote"><b>Production control rule</b><p>Any manual credit/debit, scheduled accrual, allocation approval or rejection should be persisted to an immutable audit ledger with actor, timestamp, reason and before/after values. Real brokerage P&amp;L should come from executed positions/custodian data—not be editable as if it were market performance.</p></div></main></div>
}
