"use client"
import{useEffect,useMemo,useState}from"react";import Link from"next/link";import Logo from"@/components/Logo";import type{AccountAdjustment,DailyGainRule,ShareAllocation,ShareControl,FundingMethod,TransferRequest,Account,SiteContent}from"@/lib/ops"
type Ops={accounts:Account[];allocations:ShareAllocation[];adjustments:AccountAdjustment[];dailyGain:DailyGainRule;shareControls:ShareControl[];fundingMethods:FundingMethod[];transfers:TransferRequest[];cryptoGateway:any;siteContent:SiteContent}
const money=(n=0)=>n.toLocaleString(undefined,{style:"currency",currency:"USD",maximumFractionDigits:2})
const cap=(n=0)=>n>=1e12?`${(n/1e12).toFixed(2)}T`:n>=1e9?`${(n/1e9).toFixed(1)}B`:money(n)
export default function Admin(){const[ops,setOps]=useState<Ops|null>(null),[amount,setAmount]=useState(""),[note,setNote]=useState(""),[client,setClient]=useState("")
 const load=()=>fetch("/api/admin/operations",{cache:"no-store"}).then(async r=>{if(!r.ok)throw new Error((await r.json()).error||"Admin session required");return r.json()}).then(setOps).catch(e=>alert(e.message))
 useEffect(()=>{load()},[])
 const op=async(body:any)=>{const r=await fetch("/api/admin/operations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(r.ok)setOps(d);else alert(d.error||"Action failed")}
 const pending=useMemo(()=>ops?.allocations.filter(x=>x.status==="Pending")||[],[ops])
 if(!ops)return <div className="adminLoading"><Logo/><h2>Opening Aether Control Center…</h2><p>If you are redirected, sign in with the administrator account first.</p><Link className="solidBtn" href="/login">Admin login</Link></div>
 const selected=ops.accounts.find(a=>a.id===client)||ops.accounts[0]
 return <div className="adminFrame"><aside className="adminSide"><Link href="/"><Logo/></Link><span className="adminBadge">ADMIN CONTROL</span><nav><a className="active">Overview</a><a href="#shares">Markets & prices</a><a href="#content">Homepage content</a><a href="#allocations">Allocations</a><a href="#funding">Funding</a></nav><Link href="/dashboard" className="ghostBtn">Client view</Link></aside><main className="adminMain">
 <div className="adminTop"><div><span className="eyebrow">Operations console</span><h1>Aether Control Center</h1><p>Full platform controls for accounts, prices, allocations, funding and public content.</p></div><span className="statusPill">● Administrator</span></div>
 <div className="adminStats"><div><small>Client accounts</small><b>{ops.accounts.length}</b><span>Real created accounts</span></div><div><small>Listed assets</small><b>{ops.shareControls.length}</b><span>{ops.shareControls.filter(x=>x.enabled).length} enabled</span></div><div><small>Pending allocations</small><b>{pending.length}</b><span>Need review</span></div><div><small>Pending transfers</small><b>{ops.transfers.filter(t=>t.status==="Pending").length}</b><span>Need review</span></div></div>
 <section className="panel"><div className="panelHead"><div><h3>Client balance adjustment</h3><span>Administrative ledger action</span></div></div><div className="adminFormGrid"><label>Client<select value={selected?.id||""} onChange={e=>setClient(e.target.value)}><option value="">Select client</option>{ops.accounts.map(a=><option key={a.id} value={a.id}>{a.name} · {a.email}</option>)}</select></label><label>Amount<input value={amount} onChange={e=>setAmount(e.target.value)} placeholder="+500 or -250"/></label><label className="wideControl">Reason<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Reason / reference"/></label><button className="solidBtn small" disabled={!selected} onClick={()=>selected&&op({action:"adjust-balance",userId:selected.id,userName:selected.name,amount:Number(amount),note})}>Apply adjustment</button></div></section>
 <section id="shares" className="panel allocationPanel"><div className="panelHead"><div><h3>Listed shares & ETFs</h3><span>Manual price and market-cap control</span></div></div><div className="adminMarketGrid">{ops.shareControls.map(c=><article className="adminMarketCard" key={c.symbol}><div className="marketCardTop"><div><b>{c.symbol}</b><small>{c.name}</small></div><span>{cap(c.marketCap)}</span></div><div className="adminMarketInputs"><label>Current price<input type="number" step=".01" value={c.manualPrice} onChange={e=>setOps({...ops,shareControls:ops.shareControls.map(x=>x.symbol===c.symbol?{...x,manualPrice:Number(e.target.value)}:x)})} onBlur={()=>op({action:"share-control",symbol:c.symbol,patch:{manualPrice:c.manualPrice}})}/></label><label>Market cap $<input type="number" value={c.marketCap} onChange={e=>setOps({...ops,shareControls:ops.shareControls.map(x=>x.symbol===c.symbol?{...x,marketCap:Number(e.target.value)}:x)})} onBlur={()=>op({action:"share-control",symbol:c.symbol,patch:{marketCap:c.marketCap}})}/></label><label>Enabled<input type="checkbox" checked={c.enabled} onChange={e=>op({action:"share-control",symbol:c.symbol,patch:{enabled:e.target.checked}})}/></label><label>Approval required<input type="checkbox" checked={c.approvalRequired} onChange={e=>op({action:"share-control",symbol:c.symbol,patch:{approvalRequired:e.target.checked}})}/></label></div><small className="marketAdminHint">Changing price automatically stores the previous price so client daily P/L moves with your new quote.</small></article>)}</div></section>
 <section id="content" className="panel allocationPanel"><div className="panelHead"><div><h3>Homepage objectives & offerings</h3><span>Editable public content</span></div></div><div className="adminFormGrid"><label>Hero eyebrow<input value={ops.siteContent.eyebrow} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,eyebrow:e.target.value}})}/></label><label>Hero title<input value={ops.siteContent.heroTitle} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,heroTitle:e.target.value}})}/></label><label>Hero accent<input value={ops.siteContent.heroAccent} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,heroAccent:e.target.value}})}/></label><label className="wideControl">Hero body<textarea value={ops.siteContent.heroBody} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,heroBody:e.target.value}})}/></label><label>Objectives title<input value={ops.siteContent.objectiveTitle} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,objectiveTitle:e.target.value}})}/></label><label className="wideControl">Objectives body<textarea value={ops.siteContent.objectiveBody} onChange={e=>setOps({...ops,siteContent:{...ops.siteContent,objectiveBody:e.target.value}})}/></label></div><div className="homeOfferAdminGrid">{ops.siteContent.offers.map((o,i)=><article key={o.id}><span>Offering {i+1}</span><input value={o.kicker} onChange={e=>{const offers=[...ops.siteContent.offers];offers[i]={...o,kicker:e.target.value};setOps({...ops,siteContent:{...ops.siteContent,offers}})}}/><input value={o.title} onChange={e=>{const offers=[...ops.siteContent.offers];offers[i]={...o,title:e.target.value};setOps({...ops,siteContent:{...ops.siteContent,offers}})}}/><textarea value={o.body} onChange={e=>{const offers=[...ops.siteContent.offers];offers[i]={...o,body:e.target.value};setOps({...ops,siteContent:{...ops.siteContent,offers}})}}/></article>)}</div><button className="solidBtn" onClick={()=>op({action:"site-content",patch:ops.siteContent})}>Save homepage content</button></section>
 <section id="allocations" className="panel allocationPanel"><div className="panelHead"><div><h3>Share allocation approvals</h3><span>{pending.length} pending</span></div></div><div className="allocationTable">{ops.allocations.map(a=><div className="allocTR" key={a.id}><span><b>{a.userName}</b><small>{a.userId}</small></span><span><b>{a.symbol}</b><small>{a.shares} shares</small></span><span>{money(a.value)}</span><span className={a.status.toLowerCase()}>{a.status}</span><span className="decisionBtns">{a.status==="Pending"&&<><button className="approve" onClick={()=>op({action:"allocation-status",id:a.id,status:"Approved"})}>Approve</button><button className="reject" onClick={()=>op({action:"allocation-status",id:a.id,status:"Rejected"})}>Reject</button></>}</span></div>)}</div></section>
 <section id="funding" className="panel allocationPanel"><div className="panelHead"><div><h3>Crypto deposit addresses</h3><span>Manual gateway</span></div></div><div className="shareControlGrid">{ops.cryptoGateway.addresses.map((a:any)=><div className="shareControl" key={a.id}><div><b>{a.asset}</b><small>{a.network}</small></div><label>Enabled<input type="checkbox" checked={a.enabled} onChange={e=>op({action:"crypto-address",id:a.id,patch:{enabled:e.target.checked}})}/></label><label className="wideControl">Address<input value={a.address} onChange={e=>setOps({...ops,cryptoGateway:{...ops.cryptoGateway,addresses:ops.cryptoGateway.addresses.map((x:any)=>x.id===a.id?{...x,address:e.target.value}:x)}})} onBlur={()=>op({action:"crypto-address",id:a.id,patch:{address:a.address}})}/></label></div>)}</div></section>
 </main></div>}
