"use client"
import {useEffect,useState} from "react"
import AppShell from "@/components/AppShell"
import type {FundingMethod,TransferRequest,ManualCryptoGateway} from "@/lib/ops"
const money=(n=0)=>n.toLocaleString('en-US',{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2})
function Countdown({expiresAt}:{expiresAt?:string}){const[left,setLeft]=useState(0);useEffect(()=>{const tick=()=>setLeft(expiresAt?Math.max(0,new Date(expiresAt).getTime()-Date.now()):0);tick();const id=setInterval(tick,1000);return()=>clearInterval(id)},[expiresAt]);const m=Math.floor(left/60000),s=Math.floor((left%60000)/1000);return <b className={left>0?"timerLive":"timerExpired"}>{left>0?`${String(m).padStart(2,"0")}:${String(s).padStart(2,"0")}`:"Expired"}</b>}
export default function Transfers(){
 const[methods,setMethods]=useState<FundingMethod[]>([]),[requests,setRequests]=useState<TransferRequest[]>([]),[gateway,setGateway]=useState<ManualCryptoGateway|null>(null),[available,setAvailable]=useState(0)
 const[direction,setDirection]=useState<"Deposit"|"Withdrawal">("Deposit"),[method,setMethod]=useState<"crypto"|"wire"|"paypal">("crypto"),[amount,setAmount]=useState(""),[asset,setAsset]=useState("USDT"),[network,setNetwork]=useState("TRC20"),[reference,setReference]=useState(""),[msg,setMsg]=useState(""),[created,setCreated]=useState<TransferRequest|null>(null)
 const load=()=>fetch("/api/transfers",{cache:"no-store"}).then(r=>r.json()).then(d=>{setMethods(d.methods||[]);setRequests(d.requests||[]);setGateway(d.cryptoGateway);setAvailable(d.available||0)})
 useEffect(()=>{load()},[])
 const addresses=(gateway?.addresses||[]).filter(a=>a.enabled),assets=Array.from(new Set(addresses.map(a=>a.asset))),networks=addresses.filter(a=>a.asset===asset),selectedAddress=addresses.find(a=>a.asset===asset&&a.network===network),active:any=methods.find(m=>m.id===method)
 useEffect(()=>{if(networks.length&&!networks.some(n=>n.network===network))setNetwork(networks[0].network)},[asset,network,networks])
 const submit=async()=>{setMsg("");setCreated(null);const r=await fetch("/api/transfers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({direction,method,amount:Number(amount),asset:method==="crypto"?asset:undefined,network:method==="crypto"?network:undefined,reference,destination:reference})});const d=await r.json();if(!r.ok){setMsg(d.error);return}setRequests([d.item,...requests]);setCreated(d.item);setMsg(`${direction} request created.`)}
 return <AppShell><section className="workspace modernWorkspace moneyWorkspace">
  <div className="workspaceHead appPageHead"><div><span className="eyebrow">Money</span><h1>Move money securely.</h1><p>Choose the funding method that works best for you.</p></div><div className="availablePill"><small>Available cash</small><b>{money(available)}</b></div></div>
  <div className="moneyModeSwitch"><button className={direction==="Deposit"?"active":""} onClick={()=>{setDirection("Deposit");setCreated(null);setMsg("")}}>↓ Deposit</button><button className={direction==="Withdrawal"?"active":""} onClick={()=>{setDirection("Withdrawal");setCreated(null);setMsg("")}}>↑ Withdraw</button></div>
  <div className="moneyLayout"><section className="panel moneyComposer"><div className="stepLabel"><span>1</span><div><b>Choose a method</b><small>{direction==="Deposit"?"How would you like to fund your account?":"Where should we send your funds?"}</small></div></div>
   <div className="fundMethodList">{methods.filter(m=>m.enabled).map(m=><button key={m.id} className={method===m.id?"selected":""} onClick={()=>{setMethod(m.id);setCreated(null)}}><span className="fundMethodIcon">{m.id==="crypto"?"₿":m.id==="wire"?"↗":"P"}</span><div><b>{m.label}</b><small>{m.id==="crypto"?"Crypto gateway":m.id==="wire"?"International transfer":"PayPal"}</small></div><span>›</span></button>)}</div>
   <div className="stepDivider"/><div className="stepLabel"><span>2</span><div><b>Enter details</b><small>Review the payment instructions before submitting.</small></div></div>
   <label className="moneyInputLabel">Amount<div className="moneyInput"><span>$</span><input type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/></div></label>
   {method==="crypto"&&<div className="cryptoChoiceGrid"><label>Asset<select value={asset} onChange={e=>setAsset(e.target.value)}>{assets.map(a=><option key={a}>{a}</option>)}</select></label><label>Network<select value={network} onChange={e=>setNetwork(e.target.value)}>{networks.map(n=><option key={n.network}>{n.network}</option>)}</select></label></div>}
   {method==="crypto"&&direction==="Deposit"&&!created&&<div className="methodInfoCard"><div><small>Crypto deposit</small><b>{asset} · {network}</b></div><p>Minimum {money(selectedAddress?.minDeposit||0)} · {gateway?.paymentWindowMinutes||30}-minute payment window.</p></div>}
   {method==="paypal"&&direction==="Deposit"&&<div className="methodDetailCard"><div className="methodDetailHead"><span className="fundMethodIcon">P</span><div><small>PayPal</small><b>{active?.paypalTag||"PayPal account"}</b></div></div>{active?.paymentLink&&<a className="paymentLinkBtn" href={active.paymentLink} target="_blank" rel="noreferrer">Open PayPal payment link ↗</a>}<p>{active?.instructions||"Follow the PayPal instructions provided by Aether."}</p></div>}
   {method==="wire"&&direction==="Deposit"&&<div className="methodDetailCard"><div className="methodDetailHead"><span className="fundMethodIcon">↗</span><div><small>International bank transfer</small><b>{active?.bankName||"Bank transfer"}</b></div></div><div className="bankDetailsGrid">{active?.beneficiary&&<div><small>Beneficiary</small><b>{active.beneficiary}</b></div>}{active?.accountNumber&&<div><small>Account / IBAN</small><b>{active.accountNumber}</b></div>}{active?.swift&&<div><small>SWIFT / BIC</small><b>{active.swift}</b></div>}{active?.routing&&<div><small>Routing / sort code</small><b>{active.routing}</b></div>}{active?.bankAddress&&<div className="wideDetail"><small>Bank address</small><b>{active.bankAddress}</b></div>}</div><p>{active?.instructions||"Follow the transfer instructions provided by Aether."}</p></div>}
   {method!=="crypto"&&direction==="Deposit"&&<label>Payment reference / transaction ID<input value={reference} onChange={e=>setReference(e.target.value)} placeholder={method==="paypal"?"PayPal transaction ID":"Bank transfer reference"}/></label>}
   {direction==="Withdrawal"&&<><div className="methodInfoCard"><div><small>{active?.label}</small><b>Withdrawal destination</b></div><p>Enter the destination details below. The request will be reviewed before funds are released.</p></div><label>Destination details<input value={reference} onChange={e=>setReference(e.target.value)} placeholder={method==="crypto"?`${asset} ${network} wallet address`:method==="paypal"?"PayPal email or tag":"Bank account / IBAN and beneficiary"}/></label></>}
   <button className="primaryMoneyBtn fullWidth" disabled={!Number(amount)} onClick={submit}>{method==="crypto"&&direction==="Deposit"?"Generate secure deposit request":`Submit ${direction.toLowerCase()} request`}</button>{msg&&<div className="formInfo">{msg}</div>}
   {created&&created.method==="crypto"&&created.direction==="Deposit"&&<div className="cryptoInvoice modernInvoice"><div className="invoiceTop"><div><small>Payment request</small><h3>{created.asset} on {created.network}</h3></div><Countdown expiresAt={created.expiresAt}/></div><div className="invoiceAmount"><span>Deposit amount</span><b>{money(created.amount)}</b></div><div className="cryptoAddressBox"><small>Send to this address only</small><code>{created.depositAddress}</code><button onClick={()=>navigator.clipboard?.writeText(created.depositAddress||"")}>Copy address</button></div><div className="gatewayNotice">Admin verifies the blockchain transaction manually before your account is credited.</div></div>}
  </section>
  <section className="panel transferHistory"><div className="panelHead"><div><h3>Activity</h3><span>Your recent money movements</span></div></div><div className="transferTimeline">{requests.slice(0,10).map(t=><div className="transferItem" key={t.id}><span className={`transferDirection ${t.direction.toLowerCase()}`}>{t.direction==="Deposit"?"↓":"↑"}</span><div><b>{t.direction} · {t.method.toUpperCase()}</b><small>{t.asset?`${t.asset}${t.network?` · ${t.network}`:""} · `:""}{t.createdAt}</small></div><div><b>{money(t.amount)}</b><small className={t.status.toLowerCase()}>{t.status}</small></div></div>)}{!requests.length&&<div className="cleanEmpty"><b>No money movement yet</b><span>Your deposits and withdrawals will appear here.</span></div>}</div></section></div>
 </section></AppShell>
}
