import Link from"next/link";import SiteHeader from"@/components/SiteHeader";import Logo from"@/components/Logo";import{Icon}from"@/components/Icons";import{getStore}from"@/lib/store"
export const dynamic="force-dynamic"
export default function Home(){const c=getStore().siteContent;return <div className="marketingPage"><SiteHeader/>
<section className="hero refinedHero"><div className="heroGrid"><div className="heroCopy"><span className="eyebrow">{c.eyebrow}</span><h1>{c.heroTitle}<br/><em>{c.heroAccent}</em></h1><p>{c.heroBody}</p><div className="heroActions"><Link className="solidBtn" href="/register">Open an account <Icon name="arrow" size={18}/></Link><Link className="outlineBtn" href="#objectives">What Aether offers</Link></div><div className="trustLine"><span><Icon name="shield" size={17}/> Security-first account controls</span><span>•</span><span>Human support</span></div></div><div className="aetherHeroObject"><div className="objectRing"><span>A</span></div><div className="objectNote one"><small>Invest</small><b>Leading companies & ETFs</b></div><div className="objectNote two"><small>Move money</small><b>Crypto · Wire · PayPal</b></div><div className="objectNote three"><small>Understand</small><b>Clear portfolio performance</b></div></div></div></section>
<section className="quietStrip"><div><span>One account</span><b>Across the way you build wealth.</b></div><div className="stripItems"><span>Equities</span><span>ETFs</span><span>Cash</span><span>Crypto funding</span><span>Support</span></div></section>
<section className="section objectiveIntro" id="objectives"><div className="sectionHead"><span className="eyebrow">What we are building for clients</span><h2>{c.objectiveTitle}</h2><p>{c.objectiveBody}</p></div><div className="homeOfferGrid">{c.offers.map((o,i)=><article className={`homeOfferCard offer${i+1}`} key={o.id}><div className="offerVisual"><span>0{i+1}</span><div className="offerShape"/></div><span className="eyebrow">{o.kicker}</span><h3>{o.title}</h3><p>{o.body}</p><Link href={o.href}>{o.cta} <Icon name="arrow" size={16}/></Link></article>)}</div></section>
<section className="section trustObjective"><div><span className="eyebrow">Aether standard</span><h2>{c.trustTitle}</h2><p>{c.trustBody}</p></div><div className="objectivePoints"><span>Account-specific balances</span><span>Admin-reviewed allocations</span><span>Transparent position values</span><span>Mobile-first client experience</span></div></section>
<section className="section"><div className="ctaBand"><div><span className="eyebrow">Aether Capital Markets</span><h2>A clearer way to manage capital.</h2><p>Open an account and build your financial home.</p></div><Link className="solidBtn light" href="/register">Get started <Icon name="arrow" size={18}/></Link></div></section>
<footer className="footer"><div><Logo/><p>Modern investing and private client software.</p></div><div><b>Platform</b><Link href="/markets">Markets</Link><Link href="/portfolio">Portfolio</Link><Link href="/support">Support</Link></div><div><b>Company</b><a>About</a><a>Security</a><a>Disclosures</a></div><div className="footerLegal">Aether Capital Markets is a software platform prototype. Regulated brokerage, custody and securities execution require appropriate licensing and partners before production launch.</div></footer></div>}
