"use client"
import {useEffect,useMemo,useState} from "react"
import AppShell from "@/components/AppShell"
import type {HoldingView,ShareAllocation,ShareControl} from "@/lib/ops"
const money=(n=0)=>n.toLocaleString(undefined,{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2})
const pct=(n=0)=>`${n>=0?"+":""}${n.toFixed(2)}%`

export default function Portfolio(){
 const [controls,setControls]=useState<ShareControl[]>([]),[requests,setRequests]=useState<ShareAllocation[]>([]),[holdings,setHoldings]=useState<HoldingView[]>([])
 const [available,setAvailable]=useState(0),[symbol,setSymbol]=useState("TSLA"),[amount,setAmount]=useState(""),[msg,setMsg]=useState("")
 const load=()=>Promise.all([fetch("/api/allocations",{cache:"no-store"}).then(r=>r.json()),fetch("/api/account",{cache:"no-store"}).then(r=>r.json())]).then(([a,b])=>{setControls(a.shareControls||[]);setRequests(a.requests||[]);setAvailable(a.available||0);setHoldings(b.holdings||[])})
 useEffect(()=>{load()},[])
 const ctl=useMemo(()=>controls.find(c=>c.symbol===symbol)||controls[0],[controls,symbol])
 const dollars=Number(amount||0),shares=ctl?.manualPrice?dollars/ctl.manualPrice:0
 const quoteDay=ctl?.previousPrice?((ctl.manualPrice-ctl.previousPrice)/ctl.previousPrice*100):0
 const submit=async()=>{setMsg("");const r=await fetch("/api/allocations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({symbol:ctl?.symbol,amount:dollars})});const d=await r.json();if(!r.ok){setMsg(d.error||"Could not submit");return}setRequests([d.item,...requests]);setAvailable(d.available??available-dollars);setAmount("");setMsg(d.item.status==="Pending"?"Allocation request sent for approval.":"Shares allocated.")}
 return <AppShell><section className="workspace modernWorkspace">
  <div className="workspaceHead appPageHead"><div><span className="eyebrow">Portfolio</span><h1>Invest with clarity.</h1><p>Choose an asset, enter your amount, and see the exact share quantity before requesting allocation.</p></div><div className="availablePill"><small>Available to invest</small><b>{money(available)}</b></div></div>
  <div className="portfolioSummaryStrip"><div><small>Market value</small><b>{money(holdings.reduce((n,h)=>n+h.currentValue,0))}</b></div><div><small>Unrealized P/L</small><b className={holdings.reduce((n,h)=>n+h.pnl,0)>=0?"gain":"loss"}>{money(holdings.reduce((n,h)=>n+h.pnl,0))}</b></div><div><small>Today's P/L</small><b className={holdings.reduce((n,h)=>n+h.dayPnl,0)>=0?"gain":"loss"}>{money(holdings.reduce((n,h)=>n+h.dayPnl,0))}</b></div></div>
  <div className="portfolioLayout"><section className="panel investComposer"><div className="composerHeader"><span className="eyebrow">Acquire shares</span><h3>{ctl?.name||"Choose an asset"}</h3><p>Share quantity is calculated from the current platform quote.</p></div><div className="assetSelector">{controls.filter(c=>c.enabled).map(c=><button key={c.symbol} className={c.symbol===ctl?.symbol?"selected":""} onClick={()=>setSymbol(c.symbol)}><span>{c.symbol.slice(0,2)}</span><div><b>{c.symbol}</b><small>{c.name}</small></div></button>)}</div><div className="quoteHeadline"><div><small>Current quote</small><b>{money(ctl?.manualPrice||0)}</b></div><span className={quoteDay>=0?"gain":"loss"}>{pct(quoteDay)} today</span></div><label className="moneyInputLabel">Amount to invest<div className="moneyInput"><span>$</span><input type="number" min={ctl?.minAmount||1} value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/></div></label><div className="tradePreview"><div><small>You receive</small><b>{shares.toLocaleString(undefined,{maximumFractionDigits:6})} shares</b></div><div><small>Request value</small><b>{money(dollars)}</b></div></div><button className="primaryMoneyBtn fullWidth" disabled={!dollars} onClick={submit}>Request allocation</button>{msg&&<div className="formInfo">{msg}</div>}<small className="tradeFinePrint">{ctl?.approvalRequired?"Admin approval is required before the position becomes active.":"This asset is configured for immediate allocation."}</small></section>
  <section className="panel holdingsPortfolio"><div className="panelHead"><div><h3>Holdings</h3><span>Market value and performance</span></div></div><div className="portfolioHoldingList">{holdings.map(h=><div className="portfolioHolding" key={h.id}><div className="tickerTile">{h.symbol.slice(0,2)}</div><div className="holdingIdentity"><b>{h.symbol}</b><small>{h.shares.toLocaleString(undefined,{maximumFractionDigits:5})} shares</small></div><div className="holdingCost"><small>Avg price</small><b>{money(h.entryPrice)}</b></div><div className="holdingMarket"><b>{money(h.currentValue)}</b><small className={h.pnl>=0?"gain":"loss"}>{money(h.pnl)} · {pct(h.pnlPct)}</small></div></div>)}{!holdings.length&&<div className="cleanEmpty"><b>Your portfolio is empty</b><span>Fund the account and request your first share allocation.</span></div>}</div><div className="requestSection"><div className="panelHead"><div><h3>Requests</h3><span>Awaiting and completed decisions</span></div></div><div className="miniLedger">{requests.slice(0,6).map(r=><div key={r.id}><span><b>{r.symbol} · {money(r.requestedAmount)}</b><small>{r.shares.toLocaleString(undefined,{maximumFractionDigits:6})} shares @ {money(r.price)}</small></span><strong className={r.status.toLowerCase()}>{r.status}</strong></div>)}{!requests.length&&<p className="subtle">No allocation requests yet.</p>}</div></div></section></div>
 </section></AppShell>
}
