"use client"
import {useEffect,useMemo,useState} from "react"
import AppShell from "@/components/AppShell"
import AssetLogo from "@/components/AssetLogo"
import type {HoldingView,ShareAllocation,ShareControl} from "@/lib/ops"
const money=(n=0)=>n.toLocaleString('en-US',{style:"currency",currency:"USD",minimumFractionDigits:2,maximumFractionDigits:2})
const pct=(n=0)=>`${n>=0?"+":""}${n.toFixed(2)}%`
const purchaseDate=(iso:string)=>new Date(iso).toLocaleDateString('en-US',{month:"short",day:"numeric",year:"numeric"})
export default function Portfolio(){
 const[controls,setControls]=useState<ShareControl[]>([]),[requests,setRequests]=useState<ShareAllocation[]>([]),[holdings,setHoldings]=useState<HoldingView[]>([])
 const[available,setAvailable]=useState(0),[symbol,setSymbol]=useState("TSLA"),[amount,setAmount]=useState(""),[msg,setMsg]=useState("")
 const load=()=>Promise.all([fetch("/api/allocations",{cache:"no-store"}).then(r=>r.json()),fetch("/api/account",{cache:"no-store"}).then(r=>r.json())]).then(([a,b])=>{setControls(a.shareControls||[]);setRequests(a.requests||[]);setAvailable(a.available||0);setHoldings(b.holdings||[])})
 useEffect(()=>{load()},[])
 const ctl=useMemo(()=>controls.find(c=>c.symbol===symbol)||controls[0],[controls,symbol])
 const dollars=Number(amount||0),shares=ctl?.manualPrice?dollars/ctl.manualPrice:0
 const move=ctl?.previousPrice?((ctl.manualPrice-ctl.previousPrice)/ctl.previousPrice*100):0
 async function submit(){setMsg("");const r=await fetch("/api/allocations",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({symbol:ctl?.symbol,amount:dollars})});const d=await r.json();if(!r.ok)return setMsg(d.error||"We could not send this request.");setRequests([d.item,...requests]);setAvailable(d.available??available-dollars);setAmount("");setMsg(d.item.status==="Pending"?"Request received. We’ll let you know when it is reviewed.":"Your investment is active.")}
 return <AppShell><section className="workspace modernWorkspace"><div className="workspaceHead appPageHead"><div><span className="eyebrow">Portfolio</span><h1>Invest with clarity.</h1><p>Choose an investment, enter an amount and see the share quantity before you continue.</p></div><div className="availablePill"><small>Available to invest</small><b>{money(available)}</b></div></div><div className="portfolioSummaryStrip"><div><small>Market value</small><b>{money(holdings.reduce((n,h)=>n+h.currentValue,0))}</b></div><div><small>Total gain / loss</small><b className={holdings.reduce((n,h)=>n+h.pnl,0)>=0?"gain":"loss"}>{money(holdings.reduce((n,h)=>n+h.pnl,0))}</b></div><div><small>Today</small><b className={holdings.reduce((n,h)=>n+h.dayPnl,0)>=0?"gain":"loss"}>{money(holdings.reduce((n,h)=>n+h.dayPnl,0))}</b></div></div><div className="portfolioLayout"><section className="panel investComposer"><div className="composerHeader"><span className="eyebrow">Choose an investment</span><h3>{ctl?.name||"Select an investment"}</h3><p>Your share quantity is calculated from the current Aether price.</p></div><div className="assetSelector">{controls.filter(c=>c.enabled).map(c=><button key={c.symbol} className={c.symbol===ctl?.symbol?"selected":""} onClick={()=>setSymbol(c.symbol)}><span>{c.symbol.slice(0,2)}</span><div><b>{c.symbol}</b><small>{c.name}</small></div></button>)}</div><div className="quoteHeadline"><div><small>Current price</small><b>{money(ctl?.manualPrice||0)}</b></div><span className={move>=0?"gain":"loss"}>{pct(move)} since the previous price</span></div><label className="moneyInputLabel">Amount to invest<div className="moneyInput"><span>$</span><input type="number" min={ctl?.minAmount||1} value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0.00"/></div></label><div className="tradePreview"><div><small>Estimated shares</small><b>{shares.toLocaleString('en-US',{maximumFractionDigits:6})}</b></div><div><small>Request amount</small><b>{money(dollars)}</b></div></div><button className="primaryMoneyBtn fullWidth" disabled={!dollars} onClick={submit}>Continue</button>{msg&&<div className="formInfo">{msg}</div>}<small className="tradeFinePrint">{ctl?.approvalRequired?"This investment is reviewed before it becomes active.":"This investment can become active immediately."}</small></section><section className="panel holdingsPortfolio"><div className="panelHead"><div><h3>Your investments</h3><span>Value and performance</span></div></div><div className="portfolioHoldingList">{holdings.map(h=><div className="holdingCardV2" key={h.id}>
    <div className="holdingCardTop"><AssetLogo symbol={h.symbol}/><div><b>{h.symbol}</b><small>{h.name}</small></div><div className="holdingCardPrice"><b>{money(h.currentValue)}</b><small>{h.shares.toLocaleString('en-US',{maximumFractionDigits:5})} shares</small></div></div>
    <div className="holdingCardMeta"><span>Purchased {purchaseDate(h.purchasedAt)}</span><span>Avg {money(h.entryPrice)}</span></div>
    <div className="holdingCardStats">
     <div><small>Total return</small><b className={h.pnl>=0?"gain":"loss"}>{h.pnl>=0?"+":""}{money(h.pnl)} · {pct(h.pnlPct)}</b></div>
     <div><small>Today</small><b className={h.dayPnl>=0?"gain":"loss"}>{h.dayPnl>=0?"+":""}{money(h.dayPnl)} · {pct(h.dayPct)}</b></div>
    </div>
   </div>)}{!holdings.length&&<div className="cleanEmpty"><b>No investments yet</b><span>Add money, then choose an investment when you’re ready.</span></div>}</div><div className="requestSection"><div className="panelHead"><div><h3>Recent requests</h3><span>Your latest investment decisions</span></div></div><div className="miniLedger">{requests.slice(0,6).map(r=><div key={r.id}><span><b>{r.symbol} · {money(r.requestedAmount)}</b><small>{r.shares.toLocaleString('en-US',{maximumFractionDigits:6})} shares at {money(r.price)}</small></span><strong className={r.status.toLowerCase()}>{r.status}</strong></div>)}{!requests.length&&<p className="subtle">No investment requests yet.</p>}</div></div></section></div></section></AppShell>
}
